# Compose File intended for Integration Testing.

version: "3.8"

services:
  db-integration-test:
    image: postgres:13
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon-league
