name: Deploy Back-End

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: deploying back-end changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACK_END_HOST }}
        username: ${{ secrets.BACK_END_USERNAME }}
        key: ${{ secrets.BACK_END_KEY }}
        port: ${{ secrets.BACK_END_PORT }}
        script: |
          git clone https://github.com/Tiernebre/pokemon-league-draft.git
          cd pokemon-league-draft
          git pull
          yarn install
          yarn bootstrap
          cd packages/back-end
          yarn compile
          sudo -E su
          pm2 start dist/app.js
          pm2 reload dist/app.js
