name: Deploy Front-End

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.FRONT_END_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONT_END_AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Install dependencies
          run: yarn

        - name: Bootstrap dependencies
          run: yarn bootstrap

        - name: Build
          run: cd packages/front-end && yarn compile 

        - name: Test
          run: ls -la && which npx

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: ${{ secrets.FRONT_END_S3_BUCKET }}
            bucket-region: ${{ secrets.FRONT_END_S3_BUCKET_REGION }}