name: Deploy Front-End

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: yarn && yarn bootstrap

        - name: Build
          run: cd packages/front-end && yarn compile

        - name: Deploy
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.FRONT_END_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.FRONT_END_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONT_END_AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.FRONT_END_S3_BUCKET_REGION }}   # optional: defaults to us-east-1
            SOURCE_DIR: 'build'
