name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: yarn install

    - name: Bootstrap dependencies across monorepo packages
      run: yarn bootstrap

    - name: Compile and build packages
      run: yarn compile

    - name: Run tests in each package
      run: yarn test